# Generated by Django 3.2.12 on 2022-02-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0002_auto_20220220_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['period_sequence']},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['year__year', 'period__period_sequence']},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['year']},
        ),
        migrations.RemoveField(
            model_name='period',
            name='id',
        ),
        migrations.AddField(
            model_name='period',
            name='period_name',
            field=models.CharField(default='', max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='period_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('year', 'period'), name='unique_semester'),
        ),
    ]
